name: motor_flutter
description: >-
  The Official Implementation of the Sonr Motor Node in Flutter.
  This package provides methods for Authentication, Data Management, and
  Wallet interactions for the Sonr Network.
version: 0.7.0
homepage: https://sonr.dev
repository: https://github.com/sonr-io/motor-flutter
issue_tracker: https://github.com/sonr-io/motor-flutter/issues
documentation: https://motor.build
environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"
dependencies:
  device_info_plus: ^4.1.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  path_provider: ^2.0.11
  plugin_platform_interface: ^2.0.2
  tuple: ^2.0.0
  protobuf: ^2.1.0
  fixnum: ^1.0.1
  logger: ^1.1.0
  encrypt: ^5.0.1
  fancy_password_field: ^1.0.4
  flutter_keychain: ^2.2.1
  flutter_svg: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: io.sonr.motor_flutter
        pluginClass: MotorFlutterPlugin
      ios:
        pluginClass: MotorFlutterPlugin
      macos:
        pluginClass: MotorFlutterPlugin

  assets:
    - assets/sonr-light.svg
    - assets/sonr-dark.svg
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/Manrope-Regular.ttf
          weight: 400
        - asset: assets/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/Manrope-ExtraBold.ttf
          weight: 800
